apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.1.1.50
      peer-asn: 64635 
      my-asn: 64636
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.140.1.1 - 10.140.1.254
