apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: metallb-system
  name: test-bgp-router
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-bgp-router
  template:
    metadata:
      labels:
        app: test-bgp-router
    spec:
      containers:
      - name: test-bgp-router
        image: quay.io/metallb/test-bgp-router:v0.2.0
        env:
        - name: METALLB_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - name: bird
          containerPort: 1179
        - name: quagga
          containerPort: 179
        - name: gobgp
          containerPort: 2179
        - name: http
          containerPort: 8080
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN

---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: test-bgp-router-bird
spec:
  ports:
  - name: bgp
    port: 179
    protocol: TCP
    targetPort: bird
  selector:
    app: test-bgp-router
  clusterIP: 10.233.0.7

---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: test-bgp-router-quagga
spec:
  ports:
  - name: bgp
    port: 179
    protocol: TCP
    targetPort: quagga
  selector:
    app: test-bgp-router
  clusterIP: 10.233.0.6

---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: test-bgp-router-gobgp
spec:
  ports:
  - name: bgp
    port: 179
    protocol: TCP
    targetPort: gobgp
  selector:
    app: test-bgp-router
  clusterIP: 10.233.0.5

---
apiVersion: v1
kind: Service
metadata:
  namespace: metallb-system
  name: test-bgp-router-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: test-bgp-router
  type: NodePort
