apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.233.0.7 
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.233.0.6   
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.233.0.5 
    address-pools:
    - name: my-ip-space
      cidr:
      - 10.1.1.76/32
      advertisements:
      - localpref: 100